name: Deploy to EC2 Pythonapp Backend Dev via SSM Testing
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.EC2_DEV_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.EC2_DEV_SECRET_KEY }}
          aws-region: ${{ secrets.EC2_REGION }}
      - name: Deploy memereact on EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=InstanceIds,Values=${{ secrets.EC2_DEV_INSTANCE_ID }}" \
            --parameters commands='["cd /home/ubuntu", "bash ./deployreact.sh ${{secrets.PERSONAL_ACCESS_TOKEN}} master"]' \
            --comment "Triggering deploy.sh via GitHub Actions" \
            --region ${{ secrets.EC2_REGION }}
