name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: package installtion
        run: npm install

      - name: build package
        run: npm run build

      - name: remove existing build files from html folder
        run: sudo rm -rf /var/www/html/*

      - name: copy build files to html folder
        run: sudo cp -r * /var/www/html/

      - name: Assign file permissions
        run: sudo chown -R www-data:www-data /var/www/html

      - name: Apache service restart
        run: sudo systemctl restart apache2.service
